### ISSUE TITLE
i have some questions for you

### ISSUE THREAD

**Issue by ZCG113035** [wschwanghart/topotoolbox#12]
Hello:
  I am a graduate student from Nanjing normal university of china ,i am major in the study of river cutting speed recording,but i don't know how to open topotoolbox  in  Matlab  for  the  analysis of digital elevation models . so can you tell me the application steps diagram for using topotoolbox?
i really appreciate you giving me some guidance.

**Comment by wschwanghart** [comment]
Please read the readme-file that comes with TopoToolbox, install it by setting the path, and get help using the documentation (type doc in the command window and find TopoToolbox under supplemental software).

**Comment by ZCG113035** [comment]
I am very happy to receive your reply，I am very happy to receive your reply. I can now use Topotoolbox to analyze the area I am interested in, but I now want to use Topotoolbox to select and project the river, but I did not find the relevant code in the Blog archive. May I ask Where can I find code that performs stream selection and projection functions？
 Thank you again for answering my question.

**Comment by ZCG113035** [comment]
I am very happy to receive your reply. I can now use Topotoolbox to analyze the area I am interested in, but I now want to use Topotoolbox to select and project the river, but I did not find the relevant code in the Blog archive. May I ask Where can I find code that performs stream selection and projection functions?
Thank you again for answering my question.

**Comment by ZCG113035** [comment]
I am very happy to receive your reply. I can now use Topotoolbox to analyze the area I am interested in, but I now want to use Topotoolbox to select and project the river, but I did not find the relevant code in the Blog archive. May I ask Where can I find code that performs stream selection and projection functions?
Thank you again for answering my question and I wish you a Merry Christmas in advance here.
