### ISSUE TITLE
How to choose the number of minarea pixels based on the dem cellsize you have

### ISSUE THREAD

**Issue by ZCG113035** [wschwanghart/topotoolbox#14]
In the process of analysis, we must first define the minarea pixels. I asked if the minimum area defined as alluvial channel is 0.9km ^ 2, so the dem pixel you use is 30 × 30, and your "minarea" value is 1000, but if my pixel is 90 × 90, should I choose 111?
Hope you can help me answer your doubts, thank you.

**Comment by wschwanghart** [comment]
Just seen that I never replied. Sorry. 
Sometimes, it may be better to choose minarea according to map units. Please check the 'units' option in STREAMobj.
