### ISSUE TITLE
mistake in curvature function

### ISSUE THREAD

**Issue by chinasio** [wschwanghart/topotoolbox#2]
switch ctype
    case 'profc'
        curv = - (p.^2 .* r + 2*p.*q.*s + q.^2.*t)./((p.^2 + q.^2).*(1 + p.^2 + q.^2).^(3));
    case 'tangc'
        curv = - (q.^2 .* r + 2*p.*q.*s + p.^2.*t)./((p.^2 + q.^2).*(1 + p.^2 + q.^2).^(3));
    case 'planc'
        curv = - (q.^2 .* r + 2*p.*q.*s + p.^2.*t)./((1 + p.^2 + q.^2).^(3));
    case 'meanc'
        curv = (p.^2 .* r + 2*p.*q.*s + q.^2.*t)./((p.^2 + q.^2).*(1 + p.^2 + q.^2)) ...
            - ((1+q).^2 .* r + 2*p.*q.*s + (1+p).^2.*t)./(2.*(1 + p.^2 + q.^2).^(3/2));
        
end
the tanc and profc is the same formula,

**Comment by wschwanghart** [comment]
In fact, profc and tangc did not have the same formula, but they were wrong nevertheless. The new curvature function now adopts the formulas used in Schmidt et al. (2003, p. 800). Note, however, that the planform or contour curvature equation has an error in that publication. The first term should start with fxx fy.^2.

Schmidt, J., Evans, I.S., Brinkmann, J., 2003. Comparison of polynomial models for land surface curvature calculation. International Journal of Geographical Information Science 17, 797–814. doi:10.1080/13658810310001596058
