### ISSUE TITLE
Error in FLOWobj/flowacc (line 144)         A  = flowacc_mex(FD.ix,FD.ixc,FD.size);

### ISSUE THREAD

**Issue by xhkong80158** [wschwanghart/topotoolbox#25]
I am getting error when using flowacc

invalid MEX-file
'/Users/kong/Downloads/topotoolbox-2.4/ttlem/hylands/flowacc_mex.mexmaci64'
:
dlopen(/Users/kong/Downloads/topotoolbox-2.4/ttlem/hylands/flowacc_mex.mexmaci64,
6): Symbol not found: _mexErrMsgTxt_800
  Referenced from:
  /Users/kong/Downloads/topotoolbox-2.4/ttlem/hylands/flowacc_mex.mexmaci64
    Expected in:
  /Applications/MATLAB_R2017b.app/bin/maci64/libmex.dylib
   in
  /Users/kong/Downloads/topotoolbox-2.4/ttlem/hylands/flowacc_mex.mexmaci64。
  
error in FLOWobj/flowacc (line 144)
        A  = flowacc_mex(FD.ix,FD.ixc,FD.size);

How can I solve this problem?

**Comment by wschwanghart** [comment]
Hi, see issue #19 (https://github.com/wschwanghart/topotoolbox/issues/19) to resolve this problem.
