### ISSUE TITLE
Trouble using the example workflow: Calculate river steepness

### ISSUE THREAD

**Issue by elisham98** [wschwanghart/topotoolbox#27]
Hello, 

My name is Elisha and I am a graduate student. I've recently started using topotools to aid with my research but I am inexperienced with machine languages. When trying to use the workflow from the cheatsheet I receive this error:

>> DEM = GRIDobj('KigoDEM.tif');
>> DEMf = resample(DEM,30);
>> FD = FLOWobj(DEMf);
>> S = STREAMobj(FD,'minarea',1000);
Error using FLOWobj/flowacc
Error: File: flowacc.m Line: 101 Column: 28
Incorrect use of '=' operator. To assign a value to a variable, use '='. To compare values for equality, use '=='.

Error in STREAMobj (line 154)
                W = flowacc(FD) >= minarea;

Now before this Matlab was crashing and I was receiving a segmentation violation. But after coming to GitHub I saw the quickest solution was to remove the mexfiles due to my using a MacBook. But following that debacle, I now receive this message. How can I solve this?

Thanks,
E

**Comment by wschwanghart** [comment]
Hi, this is weird. Is it possible that you are using an outdated version of TT? Line [101 in flowacc.m](https://github.com/wschwanghart/topotoolbox/blob/master/%40FLOWobj/flowacc.m) is a comment. The issue with new MacOS has been dealt with here: https://github.com/wschwanghart/topotoolbox/issues/19
Hope this works.
Best regards, Wolfgang

**Comment by elisham98** [comment]
Thanks the problem was in fact that I was using an outdated version of TT.
